#!/bin/bash

# Paramêtres
SHIPYARD_ROLE=${1:-node}
MODE=${2:-both}

# IP locale
LOCAL_IP=$(hostname -I | awk -F" " '{print $1}')

# Mise à jour de la liste des paquets
sudo apt update

# Configuration et flashage de l'image RPI
if [ $MODE != "only-rpi" ]; then
    # Installation locale de flash (https://github.com/hypriot/flash)
    if [ ! -f ./flash ]; then
        curl https://raw.githubusercontent.com/34ruedesgardes/flash/fix-customization/$(uname -s)/flash > ./flash
        chmod +x ./flash
    fi

    # Flashage de la carte
    sudo apt install -y uuid-runtime pv
    RPI_HOSTNAME="rpi-$(uuidgen)"
    sudo ./flash --device mmcblk0 --ssid ruedesgardes --password survivant75 --hostname $RPI_HOSTNAME https://downloads.hypriot.com/hypriotos-rpi-v1.0.0.img.zip << USERINPUT
mmcblk0
yes
USERINPUT

    # On attend que le RPI soit démarré avec la carte qu'on vient de flasher
    while true; do
        echo ""
        read -rp "La carte SD est prête : l'insérer dans le RaspberryPi et l'alimenter en électricité. Une fois ceci fait, écrivez \"oui\" :  " on
        case $on in
          [Oo]* ) break;;
          [Nn]* ) exit;;
          * ) echo 'Écrivez "oui" ou "non".';;
        esac
    done

    echo "On attend deux minutes le temps que le RaspberryPi démarre..."
    sleep 120
fi

# Opérations sur le RPI
if [ $MODE != "only-flash" ]; then
    # Récupération de l'IP du nouveau RPI
    # On ne peut pas servir de RPI_HOSTNAME car nmap retourne le hostname de la précédente installation
    RPI_HOSTNAME=$(nmap -sP ${LOCAL_IP}/24 | grep rpi\- | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | tail -n1)
    if [ $RPI_HOSTNAME == "" ]; then
        echo "Impossible de trouver le RaspberryPi en scannant le réseau ${LOCAL_IP}/24"
        exit 1
    fi

    # Copie des clés SSH locales sur le RPI
    ssh-keygen -R ${RPI_HOSTNAME}
    echo "hypriot" > /tmp/${RPI_HOSTNAME}-ssh-password
    sshpass -f /tmp/${RPI_HOSTNAME}-ssh-password ssh-copy-id -oStrictHostKeyChecking=no pirate@${RPI_HOSTNAME}
    rm /tmp/${RPI_HOSTNAME}-ssh-password

    # Mise à niveau des paquets
    ssh -oStrictHostKeyChecking=no pirate@${RPI_HOSTNAME} sudo apt update
    ssh -oStrictHostKeyChecking=no pirate@${RPI_HOSTNAME} sudo apt upgrade -y

    # Intégration au cluster Swarm géré par Shipyard
    if [ $SHIPYARD_ROLE == "master" ]; then
       ssh -oStrictHostKeyChecking=no pirate@${RPI_HOSTNAME} "curl -s https://raw.githubusercontent.com/janeczku/docker-shipyard-armv7/master/deploy.sh | bash -s"
    else
        sudo apt install -y nmap
        SHIPYARD_MASTER_IP=$(sudo nmap -sS -O -oG - -p 4001 ${LOCAL_IP}/24 | awk '/Up$/{print $2}' | tail -n1 )
        if [ $SHIPYARD_MASTER_IP == "" ]; then
            echo "Impossible de trouver nœud Shipyard maître"
            exit 1
        else
            ssh -oStrictHostKeyChecking=no pirate@${RPI_HOSTNAME} "curl -s https://raw.githubusercontent.com/janeczku/docker-shipyard-armv7/master/deploy.sh | ACTION=node DISCOVERY=etcd://${SHIPYARD_MASTER_IP}:4001 bash -s"
        fi
    fi
fi
