FROM mastermindg/rpi-dns:latest

ADD files/etc/bind/db.192 /etc/bind/db.192
ADD files/etc/bind/db.34ruedesgardes.org /etc/bind/db.34ruedesgardes.org
ADD files/etc/bind/named.conf.local /etc/bind/named.conf.local
ADD files/etc/bind/named.conf.options /etc/bind/named.conf.options
