version: '2'

volumes:
  bind-data: ~

services:
  bind:
    build: .
    image: mastermindg/rpi-dns:latest
    ports:
      - "53:53/udp"
      - "1000:1000"
    volumes:
      - "bind-data:/data"
    restart: always
