version: '2'

volumes:
  bind-data: ~

services:
  bind:
    image: pastishosting/rpi-dns
    ports:
      - "53:53/udp"
      - "1000:1000/tcp"
    volumes:
      - "bind-data:/data"
    restart: always
