FROM mastermindg/rpi-dns:latest

ADD files/etc/bind/db.192 /data/bind/etc/db.192
ADD files/etc/bind/db.34ruedesgardes.org /data/bind/etc/db.34ruedesgardes.org
ADD files/etc/bind/named.conf.local /data/bind/etc/named.conf.local
ADD files/etc/bind/named.conf.options /data/bind/etc/named.conf.options
