FROM mastermindg/rpi-dns:latest

COPY files/etc/bind/db.192 /etc/bind/db.192
COPY files/etc/bind/db.34ruedesgardes.org /etc/bind/db.34ruedesgardes.org
COPY files/etc/bind/named.conf.local /etc/bind/named.conf.local
